services:
  # Fake GCS Server for local testing
  fake-gcs-server:
    image: fsouza/fake-gcs-server
    ports:
      - "4443:4443"
    command: [
      "-scheme", "http",
      "-host", "0.0.0.0",
      "-port", "4443",
      "-public-host", "localhost:4443"
    ]
    volumes:
      - gcs-data:/data
    environment:
      - STORAGE_EMULATOR_HOST=localhost:4443

  # Google Cloud Pub/Sub Emulator
  pubsub-emulator:
    platform: linux/amd64  # Explicit platform for ARM64 Mac compatibility
    image: messagebird/gcloud-pubsub-emulator
    ports:
      - "8085:8681"
    environment:
      - PUBSUB_PROJECT_ID=test-project

volumes:
  gcs-data: